spring:
  application:
    name: shop
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_USERNAME:postgres}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

api:
  v1: /api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY:}
    success-url: ${TOSS_SUCCESS_URL:http://localhost:8080/payments/success.html}
    fail-url: ${TOSS_FAIL_URL:http://localhost:8080/payments/fail.html}